# Generated by Django 4.2.11 on 2024-04-03 05:55

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        default="CustomUsers/default-user-image.jpg",
                        upload_to="CustomUsers/ProfilePictures/",
                        verbose_name="Profile Photo",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+918513998991",
                        max_length=20,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "about_me",
                    models.TextField(
                        default="Say something about yourself", verbose_name="About Me"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, default="", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="City"
                    ),
                ),
                (
                    "twitter_handle",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=25,
                        verbose_name="Twitter/X Handle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
