# Generated by Django 4.2.11 on 2024-04-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="CustomUsers/demo-jp.jpg",
                upload_to="CustomUsers/ProfilePictures/",
                verbose_name="Profile Photo",
            ),
        ),
    ]
