# Generated by Django 4.2.11 on 2024-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="code_forces_handle",
            field=models.CharField(
                blank=True,
                default="",
                max_length=25,
                verbose_name="CodeForces Username",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="github_handle",
            field=models.CharField(
                blank=True, default="", max_length=25, verbose_name="Github Username"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="leetcode_handle",
            field=models.CharField(
                blank=True, default="", max_length=25, verbose_name="Leetcode Username"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="linked_in_handle",
            field=models.CharField(
                blank=True, default="", max_length=25, verbose_name="LinkedIn Username"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter_handle",
            field=models.CharField(
                blank=True, default="", max_length=25, verbose_name="Twitter/X Username"
            ),
        ),
    ]
