
# This compose file shold be run inside the server. 
# docker compose for nginx reverse proxy and portainer. see nginx reverse proxy documentation for more advanced settings.  
# create the network if already not created. 
# copy the compose file in the specified dir in the server, and then run the compose file. 
# docker compose -p algocode_auth_service_monitor -f production.yml up -d --remove-orphans 

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx_proxy_manager_data:/data
      - nginx_letsencrypt_data:/etc/letsencrypt
    networks:
      - algocode-backend-auth-service-network
      
  portainer:
    image: portainer/portainer-ce:latest 
    privileged: true
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "8000:8000"
      - "9443:9443"
      - "9000:9000"
    restart: always
    networks:
      - algocode-backend-auth-service-network



# TODO Create the network in the server 
networks:
  algocode-backend-auth-service-network:
   external: true 

volumes:
  portainer_data: {}
  nginx_proxy_manager_data: {}
  nginx_letsencrypt_data: {}
